print("Las máquinas me sorprenden con mucha frecuencia")
print()
print("Celeste")
print("23", 23)
print("Una computadora puede ser llamada \"inteligente\" si logra engañar a una persona haciéndole creer que es un humano")
print("Juan Martín", "Arenillas", "17",sep="_")
print("calle", "numero", "código postal", sep="\n")
print("Feliz", "\tprimavera", "\t\t2024", sep="\n")
print("Solo podemos ver poco del futuro", "pero lo suficiente para darnos cuenta de que hay mucho que hacer", sep=",")
print("     *")
print("    * *")
print("   *   *")
print("  *     *")
print(" ***   ***")
print("   *   *")
print("   *   *")
print("   *****")
nombre=str("Juan Martín")
apellido=str("Arenillas")
edad=int(17)
altura=int(1.70)
num_vuelo=str("CLA 43")
temperatura=str("22°C")
salario=int(205000)
fin_juego=bool(True)
num_par=bool(False)